### ISSUE TITLE
Comboboxes appear to be non-functional

### ISSUE THREAD

**Issue by kkofler** [anaselli/dnfdragora#5]
Using revision bb6edcf85175a04d9d599ab2754a5e3a6c409ef9.

I tried listing the available updates. But neither "All updates" in the first combobox nor "To update" in the filter combobox appear to do anything useful. (When I tried, I had 5 updates not installed yet according to plasma-pk-updates.)

Are those filters expected to do anything yet? If not, it may be worth hiding them until they work.

**Comment by anaselli** [comment]
Packages should be in the list, but the problem is that i show all the groups right now, so until i cannot fix the relation package->getGroup[s](), so that i can show only the related groups, i cannot fix this issue :)

**Comment by Conan-Kudo** [comment]
With 0f087230bd45eaa388e166ef6898ee09fdbe6dfe, this should be solved.

**Comment by Conan-Kudo** [comment]
With 0f087230bd45eaa388e166ef6898ee09fdbe6dfe, this should be solved.
