### ISSUE TITLE
Cannot combine filters and name search

### ISSUE THREAD

**Issue by kkofler** [anaselli/dnfdragora#8]
Using revision 7f9434092d4bb580f3e9a8ee741c8c6206d81f90.

Testing with an update not yet installed: `youtube-dl`, which is in the "Text-based Internet" group.

1. Browsing to the "Text-based Internet" group, default "All" filter: `youtube-dl` appears in the list.
2. Browsing to the "Text-based Internet" group, "To update" filter: `youtube-dl` appears (as the one result).
3. Searching for `youtube-dl` by name, default "All" filter: `youtube-dl` appears (3 results, different versions of the package).
4. Searching for `youtube-dl` by name, "To update" filter: **empty search result**.

**Comment by anaselli** [comment]
With the commit bd7b0e538be86bf411311507df6cb198f052a7f2, it should be fixed
